apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-ui
  namespace: peek
  labels:
    app: votes-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votes-ui
  template:
    metadata:
      name: votes-ui
      labels:
        app: votes-ui
    spec:
      containers:
        - name: votes-ui
          image: peek-votes-ui:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: PORT
            - name: VOTES_API_HOST
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: VOTES_API_HOST
            - name: VOTES_API_PORT
              valueFrom:
                secretKeyRef:
                  name: votes-ui-secrets
                  key: VOTES_API_PORT
      restartPolicy: Always
